apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
  labels:
    app.kubernetes.io/name: loadbalancer-example
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app.kubernetes.io/name: loadbalancer-example