apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: network-troubleshooter
  name: network-troubleshooter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: network-troubleshooter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: network-troubleshooter
    spec:
      containers:
      - image: nicolaka/netshoot:latest
        name: network-troubleshooter
